### ISSUE TITLE
Possible Bug causing blanck FBX file name

### ISSUE THREAD

**Issue by TodoCreativo** [Wildergames/blender-quick-exporter#1]
Hello there. I'm trying your addon and found a small issue while exporting in both Export Single and Export All. 
While creating a new Export Package you're requested to set a package Name and an export Path:
![image](https://user-images.githubusercontent.com/3535032/109386167-28b3e480-78f9-11eb-86cd-50519c7ee1b5.png)
As you can see I set the package Name and the folder Path where to save the FBX files.

The issue is that when exporting it generates a no-name ".fbx" file for each package, regardless the name of the package.
It occurred to me to set the name of the file directly into the Path:
![image](https://user-images.githubusercontent.com/3535032/109386223-95c77a00-78f9-11eb-8ace-e5b3a5d6b883.png)
This way it works but I think it's not intuitive and it probably isn't what people would expect.

I had a look at the code and found where the "issue" is and how to solve it. In the operators.py source file, line 64, is where you set the `path` variable:
`path = bpy.path.ensure_ext(bpy.path.abspath(package.path), '.fbx')`

I'd suggest to change it this way:
`path = bpy.path.ensure_ext(bpy.path.abspath(package.path), package.name + '.fbx')`

This way the Name of the package is used to automatically set the name of the exported FBX file without having to write it twice in the UI (considering that not everyone would try to write the name in the Path). I tried and it works well.

Hope to have helped to better this really nice addon **;)**
Cheers.

**Comment by tonycoculuzzi** [comment]
Fixed! Thanks for bringing this to my attention. My usual workflow always ended up in me adding a .fbx filename to the export path so I missed this usecase. Now, if the Path lacks a filename ending in `.fbx`, the exported filename will default to `{package.name}.fbx`. Cheers!

**Comment by TodoCreativo** [comment]
BTW, I shared the existence of your plugin in a video on my channel: [Blender Quick Exporter - Exportar FBX con 1 Click](https://www.youtube.com/watch?v=3YFmsLIrf6M&t=427s).

Cheers and keep up the good work!
